os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - "12"
cache:
  directories:
    - "$HOME/.npm"
script:
  - "npm run build"
  - "npm link && cty2json -V"
before_script:
  export GRADLE_OPTS=-Dorg.gradle.daemon=false
env:
  - YARN_GPG=no
